name: qparkin_app
description: Aplikasi QParkin Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.6.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  intl: ^0.18.1
  # get: ^4.6.6
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  
  # OSM Map Integration dependencies
  flutter_osm_plugin: ^1.3.8
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  package_info_plus: ^8.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/